version: "3.9"
services:
  # Frontend =======================
  client:
    container_name: client
    # Build the Dockerfile from the current directory
    build:
      context: .
      dockerfile: Dockerfile
    # Expose port 3000
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_URL=https://api.kcddhaka.org/api/v1/
    restart: always